name: Deploy WordPress

on:
  push:
    branches:
      - wordpress-deployment

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f mysql.yaml
        
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/wordpress-deployment
