---
name: Deploy WordPress
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        run: echo "hello world"
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f mysql.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/wordpress-deployment
